<?php
	$messages = array(
	"I hold no opinion on this website.",
	"This sucks I wanna go home.",
	"Huh?",
	"It's okay.",
	"What do you mean I'm just a php script? I'm not a php script!",
	"Absolute bollocks!",
	"My lawyer requested I don't communicate with this site anymore.",
	"...",
	"I don't feel like talking today.",
	"What's music?",
	"What's a website?",
	"I am not a fortune cookie,",
	"Looks like a web 1.0 site",
	"At least there's no geocities edgy skull gifs, yet.",
	"I'm in ur website randomizing ur testimonials",
	"Can I has testimonial?",
	"Despite the allegations I was never a race car driver.",
	"Music to my ears.",
	"Will probably look cool once it's finished.",
	"Reborn after abandonment!",
	"I LIVE!",
	"Ay Tone",
	"What's all this gabagool?",
	"You come to me girthless, on fat bear weeb.",
	"Free tidbit",
	"Free gonbong",
	"Glory to broadband kanye",
	"Aye I'm walkin' 'ere",
	"Lobu rītu!",
	"Latgale iz myužu",
	"Lobs bej puika myusu Džerijs",
	"I'm jerry dabu di dabu dai",
	"Only shooting dope, breaks the moold");
    echo $messages[rand(0, count($messages)-1)];
?>
